# temas.py
# Lista de 35 temas de oposiciones

TEMAS = [
    "La Ley 39/2015: disposiciones generales. Interesados y actividad de las Administraciones Públicas.",
    "Ley 39/2015: disposiciones sobre el procedimiento administrativo común. Garantías, iniciación, ordenación, instrucción, finalización, tramitación simplificada.",
    "Ley 39/2015: revisión de los actos en vía administrativa. Revisión de oficio y recursos administrativos.",
    "Eficacia de los actos administrativos: notificación, contenido, plazo, práctica, notificación defectuosa, publicación, ejecutividad.",
    "Invalidez del acto administrativo: nulidad de pleno derecho y anulabilidad. Principio de conservación del acto administrativo.",
    "Expediente, documento y archivo electrónico. Apoyo a la tramitación administrativa.",
    "Comunicaciones y notificaciones al ciudadano: Notific@, DEHU, PAE, OBSAE.",
    "El ciudadano como administrado: concepto, clases, capacidad y causas modificativas. Derechos en relación con la Administración.",
    "Potestad sancionadora: concepto y especialidades del procedimiento sancionador.",
    "Responsabilidad de la Administración pública: presupuestos y responsabilidad penal de autoridades y personal al servicio de las administraciones.",
    "Personal al servicio de las Administraciones públicas: derechos, deberes, incompatibilidades y régimen disciplinario.",
    "Ética pública y código de conducta del personal empleado público: deberes, principios éticos, conflictos de interés, integridad en atención al ciudadano.",
    "Protección de datos de carácter personal: principios y derechos de los ciudadanos.",
    "Funcionamiento de los órganos colegiados municipales: requisitos de celebración de sesiones.",
    "Régimen de sesiones y acuerdos de órganos de gobierno local: actas, certificaciones, comunicaciones, notificaciones, publicación y medios telemáticos.",
    "Intervención administrativa local en la actividad privada: formas de intervención y actividad de fomento.",
    "Servicio público en entidades locales: concepto y formas de gestión de servicios públicos locales.",
    "Patrimonio de las entidades locales: clases, alteración de la calificación jurídica, bienes de dominio público local.",
    "Contratos del sector público: objeto, ámbito de aplicación, tipos, partes y contrato menor.",
    "Ordenación del territorio y urbanismo en la Comunidad Valenciana: instrumentos de ordenación.",
    "Presupuesto general de las entidades locales: concepto y contenido.",
    "Tesorería de las entidades locales: régimen jurídico y principio de unidad de caja.",
    "Ley 31/1995 de Prevención de Riesgos Laborales: obligaciones, servicio de prevención, delegados y comité de seguridad y salud.",
    "Ley 19/2013 de transparencia y Ley 2/2015 de transparencia de la Comunitat Valenciana: acceso a información pública y buen gobierno.",
    "Ley Orgánica 1/2004 de protección integral contra la violencia de género y Ley 3/2007 de igualdad efectiva de mujeres y hombres: competencias municipales.",
    "Calidad del servicio al cliente: objetivos de atención al ciudadano.",
    "Oficinas de asistencia en materia de registro: funciones, reglamentos y resoluciones de funcionamiento.",
    "Herramientas tecnológicas para la atención ciudadana: registro electrónico, interoperabilidad, firma electrónica y asignación de expedientes.",
    "Habilidades sociales y comunicación: importancia de actitudes y comunicación interpersonal.",
    "Estilos de comportamiento y comunicación: no agresivo, agresivo y asertivo.",
    "Habilidades de comunicación: escucha activa, empatía, positividad, preguntas y gestión de críticas.",
    "Tratamiento de quejas y reclamaciones: afrontamiento de la agresividad.",
    "Sistemas de información transversales: SIA, Directorio y DIR3.",
    "Intercambio de información entre administraciones públicas: plataforma de intermediación de datos y adhesiones electrónicas.",
    "Gestión de la demanda y control de flujos de personas: gestión de colas, predicción de demanda, asignación de turnos, cita previa y optimización de tiempos."
]
