name: enviar-preguntas-ultradios

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install openai requests
      - name: Generar preguntas si no existen
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generar_preguntas.py
      - name: Enviar pregunta a Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python sender.py
